### ISSUE TITLE
Yallage服务器已经被复活了

### ISSUE THREAD

**Issue by Qianyiovo** [kobe-koto/Yallage#1]
哈哈哈草，无聊在github搜一下yallage还真发现了一些东西，顺便说一下Yallage服务器已经被复活了，不知道你有没有兴趣回来玩，如有打扰可以直接close掉。

**Comment by kobe-koto** [comment]
好的捏

去掉RIP提示和更新教程以以及提上日程力

thanks

**Comment by kobe-koto** [comment]
fixed in commit d6383d821f4a25ad79b3a570f1f67640ed855ecc
